### ISSUE TITLE
How to use backup to restore？

### ISSUE THREAD

**Issue by llussy** [donghoony1/Notion-Keeper-V2#1]
Hello,I have successfully backed up now, can I restore to notion through the backup file?

**Comment by donghoony1** [comment]
Hello, Thank you for your participation. There are no way to restore to Notion. But, I have a plan to make recovery feature to other services when there is a serious problem with Notion.

**Comment by llussy** [comment]
> Hello, Thank you for your participation. There are no way to restore to Notion. But, I have a plan to make recovery feature to other services when there is a serious problem with Notion.

Thanks.I also believe Notion won't be a serious problem.
